name: test_savage
description: "Test navigation system"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: any
  go_router: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_route_generator: any
  build_runner: any

flutter:
  uses-material-design: true
